#!/usr/bin/env bash

check_factor()
{
	if [ $# -ne 3 ];
        then
                args=("$@")
                count=0
                n2=1
                for a in ${args[*]};
                do
                        if [ $count -gt 1 ];
                        then
                                n2=$(echo $a*$n2 | bc)
                        fi
                        count=$((count + 1))
                done
        else
                n2=$3
        fi

        n1=$2
        num=$(echo "$1" | tr ':' '=')

        result=$(echo "if($n2 > $n1) 1 else 0" | bc)
	        if ((result == 1)); then
		        ncp=$n1
		        n1=$n2
		        n2=$ncp
                fi

        echo "$num$n1*$n2"
}

if [ $# -ne 1 ]
then
        echo 'Usage: rsa <file>'
        exit 1
else

        while read i
        do

                result=$(factor "$i")
                check_factor $result

        done < "$1"
fi
